NVCC = nvcc
NVCC_FLAGS = -std=c++11 -arch=sm_75 -O3
PHASE2_DIR = ../../phase2_gpu_basic
TRAIN_DIR = ..
INCLUDES = -I$(PHASE2_DIR)/Include

KERNELS = $(PHASE2_DIR)/src/kernels/conv2d.cu \
          $(PHASE2_DIR)/src/kernels/relu.cu \
          $(PHASE2_DIR)/src/kernels/maxpool.cu \
          $(PHASE2_DIR)/src/kernels/upsample.cu \
          $(PHASE2_DIR)/src/kernels/conv2d_backward.cu \
          $(PHASE2_DIR)/src/kernels/relu_backward.cu \
          $(PHASE2_DIR)/src/kernels/maxpool_backward.cu \
          $(PHASE2_DIR)/src/kernels/upsample_backward.cu

FORWARD_KERNELS = $(PHASE2_DIR)/src/kernels/conv2d.cu \
                  $(PHASE2_DIR)/src/kernels/relu.cu \
                  $(PHASE2_DIR)/src/kernels/maxpool.cu \
                  $(PHASE2_DIR)/src/kernels/upsample.cu

TRAIN_UTILS = $(PHASE2_DIR)/src/kernels/mse_loss.cu \
              $(TRAIN_DIR)/src/sgd_optimizer.cu

all: benchmark_full train_phase2 infer_phase2 extract_features

benchmark_full: benchmark_full.cu $(KERNELS)
	$(NVCC) $(NVCC_FLAGS) $(INCLUDES) benchmark_full.cu $(KERNELS) -o benchmark_full

train_phase2: train_phase2.cu $(KERNELS) $(TRAIN_UTILS)
	$(NVCC) $(NVCC_FLAGS) $(INCLUDES) train_phase2.cu $(KERNELS) $(TRAIN_UTILS) -o train_phase2

infer_phase2: infer_phase2.cu $(FORWARD_KERNELS)
	$(NVCC) $(NVCC_FLAGS) $(INCLUDES) infer_phase2.cu $(FORWARD_KERNELS) -o infer_phase2

extract_features: extract_features.cu $(FORWARD_KERNELS)
	$(NVCC) $(NVCC_FLAGS) $(INCLUDES) extract_features.cu $(FORWARD_KERNELS) -o extract_features

run: benchmark_full
	./benchmark_full

train: train_phase2
	./train_phase2

infer: infer_phase2
	./infer_phase2

extract: extract_features
	./extract_features

clean:
	rm -f benchmark_full train_phase2 infer_phase2 extract_features

.PHONY: all run train infer extract clean
