NVCC = nvcc
NVCC_FLAGS = -std=c++11 -arch=sm_75 -O3
PHASE3_DIR = ../../phase3_gpu_optimized
TRAIN_DIR = ..
INCLUDES = -I$(PHASE3_DIR)/Include -I$(PHASE3_DIR)/include

KERNELS = $(PHASE3_DIR)/src/kernels/im2col.cu \
          $(PHASE3_DIR)/src/kernels/gemm.cu \
          $(PHASE3_DIR)/src/kernels/relu.cu \
          $(PHASE3_DIR)/src/kernels/maxpool.cu \
          $(PHASE3_DIR)/src/kernels/upsample.cu \
          $(PHASE3_DIR)/src/kernels/conv2d_backward_gemm.cu \
          $(PHASE3_DIR)/src/kernels/relu_backward.cu \
          $(PHASE3_DIR)/src/kernels/upsample_backward.cu

FORWARD_KERNELS = $(PHASE3_DIR)/src/kernels/im2col.cu \
                  $(PHASE3_DIR)/src/kernels/gemm.cu \
                  $(PHASE3_DIR)/src/kernels/relu.cu \
                  $(PHASE3_DIR)/src/kernels/maxpool.cu \
                  $(PHASE3_DIR)/src/kernels/upsample.cu

TRAIN_UTILS = $(PHASE3_DIR)/src/kernels/mse_loss.cu \
              $(PHASE3_DIR)/src/kernels/sgd_optimizer.cu

all: benchmark_full train_phase3_v1 infer_phase3_v1 extract_features

benchmark_full: benchmark_full.cu $(KERNELS)
	$(NVCC) $(NVCC_FLAGS) $(INCLUDES) benchmark_full.cu $(KERNELS) -o benchmark_full

train_phase3_v1: train_phase3_v1.cu $(KERNELS) $(TRAIN_UTILS)
	$(NVCC) $(NVCC_FLAGS) $(INCLUDES) train_phase3_v1.cu $(KERNELS) $(TRAIN_UTILS) -o train_phase3_v1

infer_phase3_v1: infer_phase3_v1.cu $(FORWARD_KERNELS)
	$(NVCC) $(NVCC_FLAGS) $(INCLUDES) infer_phase3_v1.cu $(FORWARD_KERNELS) $(PHASE3_DIR)/src/kernels/mse_loss.cu -o infer_phase3_v1

extract_features: extract_features.cu $(FORWARD_KERNELS)
	$(NVCC) $(NVCC_FLAGS) $(INCLUDES) extract_features.cu $(FORWARD_KERNELS) -o extract_features

run: benchmark_full
	./benchmark_full

train: train_phase3_v1
	./train_phase3_v1

infer: infer_phase3_v1
	./infer_phase3_v1

extract: extract_features
	./extract_features

clean:
	rm -f benchmark_full train_phase3_v1 infer_phase3_v1 extract_features

.PHONY: all run train infer extract clean
