# 1. Trình biên dịch & Cờ
NVCC = /usr/local/cuda-12.6/bin/nvcc

INC = -I./Include 
CXXFLAGS = -O3 -std=c++17

# 2. Danh sách file nguồn (CHỈ liệt kê file, KHÔNG viết lệnh nvcc ở đây)
SRCS = src/main_gpu_optimized.cu \
       src/autoencoder.cu \
       src/kernels/im2col.cu \
       src/kernels/gemm.cu \
       src/kernels/relu.cu \
       src/kernels/maxpool.cu \
       src/kernels/upsample.cu \
       src/utils/cuda_utils.cpp \
       src/utils/gpu_memory.cu

# 3. Tên file chạy
TARGET = run_phase3

# 4. Quy tắc biên dịch
all: $(TARGET)

$(TARGET): $(SRCS)
	$(NVCC) $(CXXFLAGS) $(INC) $(SRCS) -o $(TARGET)

# 5. Dọn dẹp
clean:
	rm -f $(TARGET)

.PHONY: clean all